version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  web:
    build:
      ./web
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - redis
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
